### ISSUE TITLE
Is it possible to add trig functions: atan, acos, asin, atan2

### ISSUE THREAD

**Issue by RobertMassart** [ckormanyos/soft_double#111]
I'm trying to make a deterministic physics engine built on soft double but I would need these trig functions.

atan, acos, asin, atan2

I could probably implement them but if someone has them done already that would be great.

**Comment by ckormanyos** [comment]
Start with `asin()` in change set a429de81874ab490acdddf5502e1a50d84751927.

**Comment by ckormanyos** [comment]
> I will postpone `atan2()` until after ---

See also #119

**Comment by ckormanyos** [comment]
Hi @RobertMassart I have implemented `asin()`, `acos()` and `atan()` in the main branch now.

I still need `atan2()` and there are also other `<cmath>`-like functions still needimg implementation. I have not yet decided if I will do entire `<cmath>` support. I#ve done that in a few other projects, but it takes a lot of time. I guess eventually I will do all of it, but this will take a while.

**Comment by ckormanyos** [comment]
One more thought, I was thinking maybe one of the important aspects you are investigating is the `constexpr`-ness of `<cmath>`-like functions.

If you follow closely C++26, then these will be natively `constexpr`. OK '26 is a ways off, but GCC trunk (i.e., GCC 14) if memory serves alread has this `constexpr`-ness in `<cmath>`. So if that is interesting, watch for 26 and see how this evolves.
